Repository natura-cosmeticos/natds-ios, pull requests merged in 2020-11, with the labels that each got.

#170 chore: bumps version to 2.6.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#171 chore: updates .podspec
  NatDS.podspec
Labels: chore

#172 [DSY-1273] Updates nat button to allows icons
  NatDS.xcodeproj/project.pbxproj
  NatDSSnapShotTests/Badge/NatBadge+Snapshot+Tests.swift
  NatDSSnapShotTests/Button/NatButton+SnapShot+Tests.swift
  NatDSSnapShotTests/Button/__Snapshots__/NatButton+SnapShot+Tests/test_icon_left_side_hasValidSnapshot.1.png
  NatDSSnapShotTests/Button/__Snapshots__/NatButton+SnapShot+Tests/test_icon_left_side_hasValidSnapshot.2.txt
  NatDSSnapShotTests/Button/__Snapshots__/NatButton+SnapShot+Tests/test_icon_right_side_hasValidSnapshot.1.png
  NatDSSnapShotTests/Button/__Snapshots__/NatButton+SnapShot+Tests/test_icon_right_side_hasValidSnapshot.2.txt
  NatDSSnapShotTests/ExpansionPanel/ExpansionPanel+Snapshot+Tests.swift
  SampleApp/Sources/Sample/Components/Button/ButtonsItemViewController.swift
  Sources/Public/Components/Button/NatButton+Icon.swift
  Sources/Public/Components/Button/NatButton.swift
  Tests/Public/Components/Button/NatButton+Specs.swift
Labels: enhancement

#173 [DSY-1621] feat: 🎸 Adds new icon and updates some icon content
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedActionText.png
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedSocialManagement.png
  Sources/Public/Components/Icons/Icon.swift
  Sources/Resources/natds-icons-ios.ttf
  Tests/Public/Components/Icons/IconTests.swift
Labels: icons

#174 chore: 🤖 Bumps version to 2.7.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#175 [1652] feat: 🎸 Updates ripple animation to public access
  NatDS.xcodeproj/project.pbxproj
  Sources/Public/Animations/Pulsable.swift
Labels: animation: ripple

#176 [DSY-1649] feat: 🎸 Adds new icons
  NatDSSnapShotTests/AppBar/AppBar+Snapshot+Tests.swift
  NatDSSnapShotTests/Badge/Badgeable+Snapshot+Tests.swift
  NatDSSnapShotTests/Badge/NatBadge+Snapshot+Tests.swift
  NatDSSnapShotTests/ExpansionPanel/ExpansionPanel+Snapshot+Tests.swift
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.filledContentChannel.png
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedActionFrame.png
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedContentHandcare.png
  NatDSSnapShotTests/ValueText/ValueTextHighlight+Snapshot+Tests.swift
  Sources/Public/Components/Icons/Icon.swift
  Sources/Resources/natds-icons-ios.ttf
  Tests/Public/Components/Icons/IconTests.swift
Labels: icons

#178 [DSY-1662] New pod
  NatDS-Swift.podspec
Labels: chore

#177 Update .typo-ci.yml - Includes Icon.swift as an excluded file
  .typo-ci.yml
Labels: chore

#179 [DSY-1662] docs: updates Readme with new pod and bitrise status
  README.md
Labels: documentation

#181 [DSY-1671] chore: 🤖 Creates new NatDS.podspect
  NatDS.podspec
Labels: chore

#182 Version bump 2.8.0
  NatDS-Swift.podspec
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#183 Updates Readme
  README.md
Labels: documentation

#184 chore: removes NatDS-Swift.podspec
  NatDS-Swift.podspec
Labels: chore

#186 chore: bumps version to 2.8.1
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore
