Repository natura-cosmeticos/natds-ios, pull requests merged in 2020-08, with the labels that each got.

#115 [DSY-1275] docs: update readme
  README.md
  docs/getting-started.md
  docs/how-to-contribute.md
Labels: documentation

#116 [DSY-1251] ci: 🎡 Removes .travis.yml
  .travis.yml
Labels: CI

#117 [DSY-1303] feat: 🎸 Adds TextField label 2 lines limit
  Sources/Public/Components/Field/TextField.swift
Labels: component: TextField, enhancement

#118 chore: 🤖 Version bump 1.7.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#121 [DSY-1274] feat: 🎸 Adds bold to NatFonts.font
  SampleApp/Sources/Sample/Components/ComponentsSection.swift
  Sources/Public/DesignTokens/NatFonts.swift
Labels: enhancement

#122 [DSY-1251] ci: 🎡 Removes old lanes from make file and fast file
  Makefile
  fastlane/Fastfile
  fastlane/README.md
Labels: CI, chore

#123 chore: 🤖 Bumps version to 1.8.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#129 chore(typo-ci): update typo ci safelist
  .typo-ci.yml
Labels: chore

#130 [DSY-1371] Update components to theme change
  NatDS.xcodeproj/project.pbxproj
  NatDSSnapShotTests/ExpansionPanel/ExpansionPanel+Snapshot+Tests.swift
  Sources/Public/Components/Button/NatButton/NatButton.swift
  Sources/Public/Components/ExpansionPanel/ExpansionPanel.swift
  Sources/Public/Components/Shortcut/NatShortcut.swift
  TestHelpers/NotificationCenter/NotificationCenterSpy.swift
  Tests/Public/Components/Button/NatButton+Specs.swift
  Tests/Public/Components/Shortcut/NatShortcut+Spec.swift
Labels: component: Expansion Panel, component: NatButton, component: Shortcut

#133 [DSY-1419] refactor: 💡 Shortcut now has a new text alignment
  Sources/Public/Components/Shortcut/NatShortcut.swift
Labels: component: Shortcut
