Repository natura-cosmeticos/natds-ios, pull requests merged in 2020-10, with the labels that each got.

#157 chore: 🤖 Bumps version to 2.3.1
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#158 [DSY-1535] test: 💍 Adds tests for Aesop theme content
  NatDS.xcodeproj/project.pbxproj
  Sources/Core/Theme/SingleSourceOfTruth/Theme.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/AesopDarkTheme+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+borderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+typography+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/AesopLightTheme+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+borderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+typography+Spec.swift
  Tests/Supporting Files/TestingHelpers/Theme/StubTheme.swift
Labels: chore

#160 [DSY-1535] test: 💍 Adds tests for Natura theme content
  NatDS.xcodeproj/project.pbxproj
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/NaturaDarkTheme+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+borderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+typography+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/NaturaLightTheme+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+borderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+typography+Spec.swift
Labels: chore

#161 [DSY-1535] test: 💍 Adds tests for The Body Shop theme content
  NatDS.xcodeproj/project.pbxproj
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/TheBodyShopDarkTheme+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+BorderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Typography+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/TheBodyShopLightTheme+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+BorderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Typography+Spec.swift
Labels: chore

#162 [DSY 1535] - refactor: 💡 Changes theme tests names to conform to the pattern
  NatDS.xcodeproj/project.pbxproj
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+BorderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+Elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+Opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+Size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+Spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+Typography+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+BorderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+Elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+Opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+Size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+Spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+Typography+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+BorderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+Elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+Opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+Size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+Spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+Typography+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+BorderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+Elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+Opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+Size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+Spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+Typography+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+BorderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Typography+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+BorderRadius+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Elevation+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Opacity+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Size+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Spacing+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Typography+Spec.swift
Labels: chore

#164 [DSY-1566] feat: 🎸 Adds new icons
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedActionRequestspecial.png
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedContentProductshowcase.png
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedProductPerfumery.png
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedProductPerfumeryfeminine.png
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedProductPerfumerymasculine.png
  NatDSSnapShotTests/Icons/__Snapshots__/Icon+Snapshot+Tests/assert-icon.outlinedProductPerfumerytbs.png
  Sources/Public/Components/Icons/Icon.swift
  Sources/Resources/natds-icons-ios.ttf
  Tests/Public/Components/Icons/IconTests.swift
Labels: icons

#165 chore: 🤖 Bumps version to 2.4.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#163 [DSY-1471] fix: 🐛 Fixes shortcut animation on tap when in a header context
  NatDS.xcodeproj/project.pbxproj
  NatDSSnapShotTests/IconButton/__Snapshots__/NatIconButton+Snapshot+Tests/test_style_standard_color_default_pressed_hasValidSnapshot.1.txt
  NatDSSnapShotTests/IconButton/__Snapshots__/NatIconButton+Snapshot+Tests/test_style_standard_color_default_tapped_hasValidSnapshot.2.txt
  NatDSSnapShotTests/IconButton/__Snapshots__/NatIconButton+Snapshot+Tests/test_style_standard_color_primary_pressed_hasValidSnapshot.1.txt
  NatDSSnapShotTests/IconButton/__Snapshots__/NatIconButton+Snapshot+Tests/test_style_standard_color_primary_tapped_hasValidSnapshot.2.txt
  Sources/Core/Animations/Pulsable.swift
  Sources/Core/Animations/PulseContainerLayer.swift
  Sources/Core/Animations/PulseLayer.swift
  Sources/Public/Components/Button/NatButton.swift
  Sources/Public/Components/IconButton/NatIconButton.swift
  Sources/Public/Components/Shortcut/NatShortcut.swift
  Tests/Public/Components/Button/PulseLayerTests.swift
  Tests/Public/Components/Button/Pusable/Pulsable+Spec.swift
  Tests/Public/Components/Button/Pusable/PulseContainerLayer+Spec.swift
  Tests/Public/Components/Button/Pusable/PulseLayer+Spec.swift
  Tests/Public/Components/Shortcut/NatShortcut+Spec.swift
Labels: bug

#167 [DSY-1592] Updates shortcut label
  NatDS.xcodeproj/project.pbxproj
  NatDSSnapShotTests/IconButton/NatIconButton+Snapshot+Tests.swift
  NatDSSnapShotTests/ShortCut/NatShortcut+Snapshot+Tests.swift
  NatDSSnapShotTests/ShortCut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_default_hasValidSnapshot.1.png
  NatDSSnapShotTests/ShortCut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_primary_hasValidSnapshot.1.png
  NatDSSnapShotTests/ShortCut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_default_hasValidSnapshot.1.png
  NatDSSnapShotTests/ShortCut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_primary_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/NatShortcut+Snapshot+Tests.swift
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_default_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_default_with_ellipsis_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_primary_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_primary_with_ellipsis_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_default_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_default_with_ellipsis_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_primary_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_primary_with_ellipsis_hasValidSnapshot.1.png
  SampleApp/Sources/Sample/Components/Shortcut/ShortcutItemViewController.swift
  Sources/Public/Components/Shortcut/NatShortcut.swift
Labels: component: Shortcut

#168 chore: bumps version to 2.5.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore
