Repository natura-cosmeticos/natds-ios, pull requests merged in 2020-06, with the labels that each got.

#80 [DSY-988] - Updates token sizes internally generated by external tool
  NatDS.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Design/Size/SizeViewController.swift
  Sources/Core/DesignTokens/Sizes.swift
  Sources/Core/Theme/SupportedBrands/Avon/AvonSizes.swift
  Sources/Core/Theme/SupportedBrands/Natura/NaturaSizes.swift
  Sources/Core/Theme/SupportedBrands/TheBodyShop/TheBodySystemSize.swift
  Sources/Public/Components/Button/NatButton/NatButton+Height.swift
  Sources/Public/DesignTokens/NatSizes.swift
  Tests/Core/SupportedBrands/Avon/AvonSize+Spec.swift
  Tests/Core/SupportedBrands/Avon/AvonSizes+Spec.swift
  Tests/Core/SupportedBrands/Natura/NaturaSize+Spec.swift
  Tests/Core/SupportedBrands/Natura/NaturaSizes+Spec.swift
  Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopSize+Spec.swift
  Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopSizes+Spec.swift
  Tests/Public/Components/Button/NatButton+Height+Spec.swift
  Tests/Public/DesignTokens/NatSizes+Spec.swift
Labels: enhancement, internal

#81 [DSY-935] Fixes NatButton animation color and border radius
  NatDS.xcodeproj/project.pbxproj
  Sources/Public/Components/Button/Pulsable.swift
  Sources/Public/Components/Button/PulseContainerLayer.swift
  Tests/Public/Components/Button/Pusable/Pulsable+Spec.swift
  Tests/Public/Components/Button/Pusable/PulseContainerLayer+Spec.swift
Labels: bug

#83 Bump version to 1.0.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: internal

#84 Updates NatButton docs.
  Sources/Public/Components/Button/NatButton/NatButton.swift
Labels: documentation

#86 [DSY-1104] Dialog standard style.
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/ComponentsSection.swift
  SampleApp/Sources/Sample/Components/Dialog/DialogItemViewController.swift
  Sources/Core/ViewStyling/Dialog/DialogStandardStyle+BodyView.swift
  Sources/Core/ViewStyling/Dialog/DialogStandardStyle+FooterView.swift
  Sources/Core/ViewStyling/Dialog/DialogStandardStyle+TitleView.swift
  Sources/Core/ViewStyling/Dialog/DialogStandardStyle.swift
  Sources/Public/Components/Button/NatButton/NatButton+Height.swift
  Sources/Public/Components/Button/NatButton/NatButton.swift
  Sources/Public/Components/Dialog/Builders/NatDialogController+ButtonConfiguration.swift
  Sources/Public/Components/Dialog/Builders/NatDialogController+StandardStyleBuilder.swift
  Sources/Public/Components/Dialog/NatDialogController.swift
  Sources/Public/DesignSystem.swift
  Sources/Public/DesignTokens/NatBorderRadius.swift
  Sources/Public/DesignTokens/NatColors.swift
  Sources/Public/DesignTokens/NatElevation.swift
  Sources/Public/DesignTokens/NatFonts.swift
  Sources/Public/DesignTokens/NatOpacities.swift
  Sources/Public/DesignTokens/NatSizes.swift
  Sources/Public/DesignTokens/NatSpacing.swift
  Tests/Core/ViewStyle/Dialog/DialogStandardStyle+BodyView+Spec.swift
  Tests/Core/ViewStyle/Dialog/DialogStandardStyle+FooterView+Spec.swift
  Tests/Core/ViewStyle/Dialog/DialogStandardStyle+TitleView+Spec.swift
  Tests/Public/Components/Button/NatButton+Specs.swift
  Tests/Public/Components/Dialog/Builders/NatDialogController+StandardStyleBuilder+Spec.swift
  Tests/Public/Components/Dialog/NatDialogController+Spec.swift
  Tests/Public/SnapShot/NatDialogController+Snapshot+Tests.swift
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_minimum_contraints_for_size_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_with_vertical_buttons_hasValidSnapshot@2x.png
Labels: enhancement

#87 chore: add support to Typo CI
  .typo-ci.yml
Labels: internal

#88 feat: 🎸 [DSY-1104] add elevation to Dialog
  Sources/Public/Components/Dialog/NatDialogController.swift
  Tests/Public/SnapShot/NatDialogController+Snapshot+Tests.swift
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_minimum_constraints_for_size_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_minimum_contraints_for_size_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_with_vertical_buttons_hasValidSnapshot@2x.png
Labels: component: Dialog, enhancement

#91 chore: ignore pbxproj files when looking for typos
  .typo-ci.yml
Labels: chore

#89 [DSY-412] Updates Natbutton: Colors for disabled + EdgeInsets.
  NatDS.xcodeproj/project.pbxproj
  Sources/Core/ViewStyling/Button/ButtonContainedStyle.swift
  Sources/Core/ViewStyling/Button/ButtonStyle.swift
  Sources/Public/Components/Button/NatButton/NatButton+EdgeInsets.swift
  Sources/Public/Components/Button/NatButton/NatButton+Height.swift
  Tests/Core/ViewStyle/Button/ButtonContainedStyle+Spec.swift
  Tests/Core/ViewStyle/Button/ButtonOutlinedStyle+Spec.swift
  Tests/Core/ViewStyle/Button/ButtonStyle+Spec.swift
  Tests/Core/ViewStyle/Button/ButtonTextStyle+Spec.swift
  Tests/Public/Components/Button/NatButton+EdgeInsets+Spec.swift
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_with_vertical_buttons_hasValidSnapshot@2x.png
Labels: a11y, component: NatButton, enhancement

#90 chore: 🤖 bumping version to 1.1.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#94 [DSY-1170] refactor: 💡 Changes default icon for drawer component
  Sources/Public/Components/NavigationDrawer/NavigationDrawerItemCell.swift
  Tests/Public/Components/NavigationDrawer/NavigationDrawerItemCellTests.swift
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_disabledStateWithSubItems_hasDisabledSnapshotWithArrow@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_disabledStateWithoutSubItems_hasDisabledSnapshotWithoutArrow@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_largeText_textHasNoLineBreak@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_normalStateWithSubItems_hasNormalSnapshotWithArrow@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_normalStateWithoutSubItems_hasNormalSnapshotWithoutArrow@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_selectedStateWithSubItems_hasSelectedSnapshotWithArrow@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_selectedStateWithoutSubItems_hasSelectedSnapshotWithoutArrow@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerTests/test_cellForRowAt_whenItIsACollapsedItem_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerTests/test_cellForRowAt_whenItIsAnExpandedItem_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NavigationDrawerTests/test_cellForRowAt_whenItIsAnItem_hasValidSnapshot@2x.png
Labels: chore, component: Drawer

#95 [DSY-1179] refactor: 💡 Adds deprecated tag to Colors and Fonts
  Sources/Public/DesignTokens/DeprecatedWillBeRemoved/Colors.swift
  Sources/Public/DesignTokens/DeprecatedWillBeRemoved/Fonts.swift
Labels: chore

#93 [DSY-1052] Create Expansion Panel - Simple and Opened ( without legend )
  Gemfile.lock
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/ComponentsSection.swift
  SampleApp/Sources/Sample/Components/ExpansionPanel/ExpansionPanelViewController.swift
  Sources/Core/Extensions/UIView+Frame.swift
  Sources/Core/Wrappers/ViewAnimatingWrapper.swift
  Sources/Public/Components/ExpansionPanel/ExpansionPanel+Margin.swift
  Sources/Public/Components/ExpansionPanel/ExpansionPanel.swift
  Tests/Core/Extensions/NSMutableAttributedString+BuilderTests.swift
  Tests/Core/Extensions/String+IconTests.swift
  Tests/Core/Extensions/UICollectionView+ReusableTests.swift
  Tests/Core/Extensions/UIColor+HexTests.swift
  Tests/Core/Extensions/UIFont+IconTests.swift
  Tests/Core/Extensions/UITableView+ReusableTests.swift
  Tests/Core/Extensions/UIView+FrameTests.swift
  Tests/Core/Wrappers/Mocks/ViewAnimatingMock.swift
  Tests/Public/Components/ExpansionPanel/ExpansionPanel+MarginTests.swift
  Tests/Public/Components/ExpansionPanel/ExpansionPanelBuilder.swift
  Tests/Public/Components/ExpansionPanel/ExpansionPanelTests.swift
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_defaultInit_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_defaultInit_withLongSubtitle_andLimitedSize_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_defaultInit_withLongSubtitle_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_initWithViewAnimating_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_initWithViewAnimating_withLongSubtitle_andLimitedSize_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_initWithViewAnimating_withLongSubtitle_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_removeDetailView_AndPanelIsExpanded_showsButtonPointingDown@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_setDetailView_whenPanelIsExpanded_showsButtonPointingUp_AndDetailView@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_tapButtonOnce_showsButtonPointingUp@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_tapButtonOnce_withDetailView_showsButtonPointingUp_AndDetailView@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_tapButtonThrice_showsButtonPointingUp@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_tapButtonTwice_showsButtonPointingDown@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_tapPanelOnce_withDetailView_showsButtonPointingUp_AndDetailView@2x.png
  Tests/ReferenceImages_64/NatDSTests.ExpansionPanelTests/test_tapPanelToCollapse_whenSetDetailView_AndPanelIsExpanded_showsButtonPointingDown@2x.png
  fastlane/README.md
Labels: component: Expansion Panel, enhancement
