Repository natura-cosmeticos/natds-ios, pull requests merged in 2020-07, with the labels that each got.

#98 [DSY-1188] Dialog dismissible property
  NatDS.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/Dialog/DialogItemViewController.swift
  Sources/Public/Components/Dialog/Builders/NatDialogController+AlertStyleBuilder.swift
  Sources/Public/Components/Dialog/Builders/NatDialogController+StandardStyleBuilder.swift
  Sources/Public/Components/Dialog/Builders/Protocols/NatDialogBodyConfigurable.swift
  Sources/Public/Components/Dialog/Builders/Protocols/NatDialogBuilder.swift
  Sources/Public/Components/Dialog/Builders/Protocols/NatDialogCustomBodyConfigurable.swift
  Sources/Public/Components/Dialog/Builders/Protocols/NatDialogCustomBodyConfigurator.swift
  Sources/Public/Components/Dialog/Builders/Protocols/NatDialogDismissableConfigurable.swift
  Sources/Public/Components/Dialog/Builders/Protocols/NatDialogTitleConfigurable.swift
  Sources/Public/Components/Dialog/DialogViewModel.swift
  Sources/Public/Components/Dialog/NatDialogController.swift
  Tests/Public/Components/Dialog/Builders/NatDialogController+AlertStyleBuilder+Spec.swift
  Tests/Public/Components/Dialog/Builders/NatDialogController+StandardStyleBuilder+Spec.swift
  Tests/Public/Components/Dialog/Builders/NatDialogController+ViewModel+Spec.swift
  Tests/Public/Components/Dialog/Builders/Protocols/NatDialogBodyConfigurable+Spec.swift
  Tests/Public/Components/Dialog/Builders/Protocols/NatDialogCustomBodyConfigurable+Spec.swift
  Tests/Public/Components/Dialog/Builders/Protocols/NatDialogDismissableConfigurable+Spec.swift
  Tests/Public/Components/Dialog/Builders/Protocols/NatDialogTitleConfigurable+Spec.swift
Labels: component: Dialog, enhancement

#99 chore: 🤖 Bumps Version to 1.3.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#100 [DSY-942] Shortcut
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/ComponentsSection.swift
  SampleApp/Sources/Sample/Components/Shortcut/ShortcutItemViewController.swift
  SampleApp/Sources/Sample/Design/Spacing/SpacingViewController.swift
  Sources/Core/ViewStyling/Shortcut/ShortcutContainedStyle.swift
  Sources/Core/ViewStyling/Shortcut/ShortcutOutlinedStyle.swift
  Sources/Public/Components/ExpansionPanel/ExpansionPanel.swift
  Sources/Public/Components/Shortcut/NatShortcut+Style.swift
  Sources/Public/Components/Shortcut/NatShortcut+Widths.swift
  Sources/Public/Components/Shortcut/NatShortcut.swift
  Sources/Public/DesignTokens/NatSpacing.swift
  Tests/Core/Animations/Pulsable.swift
  Tests/Core/Animations/PulseContainerLayer.swift
  Tests/Core/Animations/PulseLayer.swift
  Tests/Core/ViewStyle/Shortcut/ShortcutContainedStyle+Spec.swift
  Tests/Core/ViewStyle/Shortcut/ShortcutOutlinedStyle+Spec.swift
  Tests/Public/Components/Button/NatButton+Specs.swift
  Tests/Public/Components/Dialog/Builders/Protocols/NatDialogBodyConfigurable+Spec.swift
  Tests/Public/Components/Shortcut/NatShortcut+Spec.swift
  Tests/Public/Components/Shortcut/NatShortcut+Widths+Spec.swift
  Tests/Public/DesignTokens/NatSpacing+Spec.swift
  Tests/Public/SnapShot/NatShortcut+Snapshot+Tests.swift
  Tests/ReferenceImages_64/NatDSTests.NatShortcutSnapshotTests/test_shortcut_style_contained_default_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatShortcutSnapshotTests/test_shortcut_style_contained_primary_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatShortcutSnapshotTests/test_shortcut_style_outlined_default_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatShortcutSnapshotTests/test_shortcut_style_outlined_primary_hasValidSnapshot@2x.png
  Tests/Supporting Files/TestingHelpers/UIGestureRecognizer+SendGesturesEvent.swift
Labels: component: Shortcut, enhancement

#102 chore: 🤖 Bumps version to 1.4.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#103 fix: 🐛 animation files at wrong location
  NatDS.xcodeproj/project.pbxproj
  Sources/Core/Animations/Pulsable.swift
  Sources/Core/Animations/PulseContainerLayer.swift
  Sources/Core/Animations/PulseLayer.swift
Labels: bug

#105 [DSY-942] docs: ✏️ Adds docs to shortcut component
  Sources/Public/Components/Shortcut/NatShortcut.swift
Labels: component: Shortcut

#104 chore: add "enum" to safelist to .typo-ci.yml
  .typo-ci.yml
Labels: chore

#101 [DSY-272] Badge
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/Badge/BadgeViewController.swift
  SampleApp/Sources/Sample/Components/ComponentsSection.swift
  Sources/Public/Components/Badge/NatBadge+Color.swift
  Sources/Public/Components/Badge/NatBadge+Style.swift
  Sources/Public/Components/Badge/NatBadge.swift
  Sources/Public/Components/Badge/Protocol/Badgeable.swift
  Tests/Public/Components/Badge/NatBadge+Color+Spec.swift
  Tests/Public/Components/Badge/NatBadge+Spec.swift
  Tests/Public/Components/Badge/Protocol/Badgeable+Spec.swift
  Tests/Public/Components/Badge/Stub/BadgeableStub.swift
  Tests/Public/SnapShot/Badgeable+Snapshot+Tests.swift
  Tests/Public/SnapShot/NatBadge+Snapshot+Tests.swift
  Tests/ReferenceImages_64/NatDSTests.BadgeableSnapshotTests/test_badge_style_standard_alert_count_100_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.BadgeableSnapshotTests/test_badge_style_standard_alert_count_1_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatBadgeSnapshotTests/test_badge_style_standard_alert_count_100_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatBadgeSnapshotTests/test_badge_style_standard_alert_count_1_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.NatBadgeSnapshotTests/test_badge_style_standard_alert_count_50_hasValidSnapshot@2x.png
Labels: component: Badge, enhancement

#106 [DSY-1215] Logo
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/ChooseBrandViewController.swift
  SampleApp/Sources/Sample/Components/ComponentsSection.swift
  SampleApp/Sources/Sample/Components/LogoItemViewController.swift
  Sources/Public/Components/Icons/NatLogoImages.swift
  Sources/Public/Components/Shortcut/NatShortcut.swift
  Sources/Resources/Images.xcassets/Logo/Avon/Contents.json
  Sources/Resources/Images.xcassets/Logo/Avon/Horizontal.imageset/Contents.json
  Sources/Resources/Images.xcassets/Logo/Avon/Horizontal.imageset/Logo-Avon-DarkHorizontal.pdf
  Sources/Resources/Images.xcassets/Logo/Avon/Horizontal.imageset/Logo-Avon-LightHorizontal.pdf
  Sources/Resources/Images.xcassets/Logo/Avon/Vertical.imageset/Contents.json
  Sources/Resources/Images.xcassets/Logo/Avon/Vertical.imageset/Logo-Avon-DarkVertical.pdf
  Sources/Resources/Images.xcassets/Logo/Avon/Vertical.imageset/Logo-Avon-LightVertical.pdf
  Sources/Resources/Images.xcassets/Logo/Contents.json
  Sources/Resources/Images.xcassets/Logo/Natura/Contents.json
  Sources/Resources/Images.xcassets/Logo/Natura/Horizontal.imageset/Contents.json
  Sources/Resources/Images.xcassets/Logo/Natura/Horizontal.imageset/Logo-NaturaCosmeticos-DarkHorizontal.pdf
  Sources/Resources/Images.xcassets/Logo/Natura/Horizontal.imageset/Logo-NaturaCosmeticos-Horizontal.pdf
  Sources/Resources/Images.xcassets/Logo/Natura/Vertical.imageset/Contents.json
  Sources/Resources/Images.xcassets/Logo/Natura/Vertical.imageset/Logo-NaturaCosmeticos-DarkVertical.pdf
  Sources/Resources/Images.xcassets/Logo/Natura/Vertical.imageset/Logo-NaturaCosmeticos-Vertical.pdf
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/Contents.json
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/Horizontal.imageset/Contents.json
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/Horizontal.imageset/Logo-TheBodyShop-DarkHorizontal.pdf
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/Horizontal.imageset/Logo-TheBodyShop-LightHorizontal.pdf
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/Vertical.imageset/Contents.json
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/Vertical.imageset/Logo-TheBodyShop-DarkVertical.pdf
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/Vertical.imageset/Logo-TheBodyShop-LightVertical.pdf
  Tests/Public/NatLogoImages+Spec.swift
Labels: enhancement

#109 chore: 🤖 Bumps version to 1.5.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#110 [DSY-1232] feat: add new icons
  Sources/Public/Components/Icons/Icon.swift
  Sources/Resources/natds-icons.ttf
  Tests/Public/Components/Icons/IconTests.swift
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandFacebook@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandGoogle@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandInstagram@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandLinkedin@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandPinterest@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandSpotify@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandTwitter@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandWhatsapp@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_filledBrandYoutube@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_outlinedPlaceRocket@2x.png
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_outlinedPlaceRunningtruck@2x.png
Labels: enhancement, icons

#111 [DSY-1232] feat: 🎸 Update icons from .tff
  Sources/Public/Components/Icons/Icon.swift
  Sources/Resources/natds-icons.ttf
  Tests/Public/Components/Icons/IconTests.swift
  Tests/ReferenceImages_64/NatDSTests.IconTests/test_icons_hasValidSnapshot_outlinedAlertNotification@2x.png
Labels: enhancement, icons

#112 [DSY-954] Update textfield
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/Button/ButtonsItemViewController.swift
  SampleApp/Sources/Sample/Components/Field/TextFieldItemViewController.swift
  SampleApp/Sources/Sample/Components/Iconography/Helper/IconCollectionViewCell.swift
  SampleApp/Sources/Sample/Components/Iconography/IconographyItemViewController.swift
  SampleApp/Sources/Sample/Design/Colors/Cells/ColorsCell.swift
  SampleApp/Sources/Sample/Design/Colors/Cells/ColorsHeaderView.swift
  Sources/Public/Components/Field/TextField.swift
  Tests/Public/Components/Field/TextFieldTests.swift
Labels: component: TextField, enhancement

#107 chore: add words to Typo CI safelist
  .typo-ci.yml
Labels: chore

#113 chore: add "sut" to Typo CI safelist
  .typo-ci.yml
Labels: chore

#108 [DSY-1018] Appbar standard
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/AppBar/AppBarDataSource.swift
  SampleApp/Sources/Sample/Components/AppBar/AppBarDetailViewController.swift
  SampleApp/Sources/Sample/Components/AppBar/AppBarViewController.swift
  SampleApp/Sources/Sample/Components/Bar/AppSearchBarViewController.swift
  SampleApp/Sources/Sample/Components/ComponentsSection.swift
  Sources/Public/Components/AppBar/UIBarButtonItem+Icon.swift
  Sources/Public/Components/AppBar/UINavigationController+Configure.swift
  Sources/Public/Components/AppBar/UINavigationController+Style.swift
  Sources/Public/Components/AppBar/UIViewController+Configure.swift
  Sources/Public/Components/AppBar/UIViewController+TitleStyle.swift
  Sources/Public/Components/Badge/Protocol/Badgeable.swift
  Sources/Public/Components/Icons/IconView.swift
  Tests/Public/Components/AppBar/Stub/StubSelector.swift
  Tests/Public/Components/AppBar/UIBarButtonItem+Icon+Spec.swift
  Tests/Public/Components/AppBar/UINavigationController+Configure+Spec.swift
  Tests/Public/Components/AppBar/UINavigationController+Style+Spec.swift
  Tests/Public/Components/AppBar/UIViewController+Configure+Spec.swift
  Tests/Public/Components/Icons/IconViewSpec.swift
  Tests/Public/SnapShot/AppBar+Snapshot+Tests.swift
  Tests/ReferenceImages_64/NatDSTests.AppBarSnapshotTests/test_appbar_style_default_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.AppBarSnapshotTests/test_appbar_style_default_logo_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.AppBarSnapshotTests/test_appbar_style_default_rightbuttons_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.AppBarSnapshotTests/test_appbar_style_default_title_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.BadgeableSnapshotTests/test_badge_style_standard_alert_count_100_hasValidSnapshot@2x.png
  Tests/ReferenceImages_64/NatDSTests.BadgeableSnapshotTests/test_badge_style_standard_alert_count_1_hasValidSnapshot@2x.png
Labels: component: AppBar, enhancement

#114 Version bump 1.6.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore
