Repository natura-cosmeticos/natds-ios, pull requests merged in 2020-12, with the labels that each got.

#180 [DSY-1437] Progress indicator circular
  NatDS.xcodeproj/project.pbxproj
  NatDSSnapShotTests/ProgressIndicator/ProgressIndicatorCircular+Snapshot+Tests.swift
  NatDSSnapShotTests/ProgressIndicator/__Snapshots__/ProgressIndicatorCircular+Snapshot+Tests/test_progress_indicator_circular_hasValidSnapshot.1.png
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/ComponentsSection.swift
  SampleApp/Sources/Sample/Components/ProgressIndicator/ProgressIndicatorItemViewController.swift
  Sources/Public/Components/IconButton/NatIconButton.swift
  Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular+Size.swift
  Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular.swift
  Tests/Public/Components/ProgressIndicator/ProgressIndicatorCircular+Spec.swift
Labels: enhancement

#190 chore: bumps version to 2.9.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  Sources/Public/Components/IconButton/NatIconButton.swift
Labels: chore

#191 Updates index documentation
  docs/documentation/index.html
Labels: chore

#197 chore: 🤖 Bumps version to 2.10.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#201 docs: updates 'how to contribute' docs
  docs/getting-started.md
  docs/how-to-contribute.md
Labels: documentation

#199 Updates README
  README.md
  docs/getting-started.md
  docs/how-to-contribute.md
Labels: documentation

#202 chore: bumps version to 2.10.1
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#203 Adds icons docs
  README.md
  docs/getting-started.md
  docs/how-to-contribute.md
  docs/using-icons.md
Labels: documentation

#207 [DSY-1747, DSY-1751] Update TBS tokens and logo
  Sources/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShop/TheBodyShopDarkTheme.swift
  Sources/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShop/TheBodyShopLightTheme.swift
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/HorizontalDark.imageset/Logo-TheBodyShop-DarkHorizontal.pdf
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/HorizontalLight.imageset/Logo-TheBodyShop-LightHorizontal.pdf
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/VerticalDark.imageset/Logo-TheBodyShop-DarkVertical.pdf
  Sources/Resources/Images.xcassets/Logo/TheBodyShop/VerticalLight.imageset/Logo-TheBodyShop-LightVertical.pdf
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Color+Spec.swift
  Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Color+Spec.swift
Labels: chore

#206 chore: change pipeline to deploy docs on branches
  .cicd/build.sh
  .cicd/copy-docs.sh
  .cicd/integration-test.sh
  .cicd/package.sh
  .cicd/unit-test.sh
Labels: chore

#208 chore: bumps version to 2.11.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore
