Repository natura-cosmeticos/natds-ios, pull requests merged in 2021-01, with the labels that each got.

#210 [DSY-1758] Textfield NatDSIcons
  NatDSSnapShotTests/TextField/__Snapshots__/TextField+Snapshot+Tests/test_state_whenHasErrorAndLargeMessageWithSmallWidth_returnMultipleErrorLinesAndNotCutIconSnapshot.1.png
  NatDSSnapShotTests/TextField/__Snapshots__/TextField+Snapshot+Tests/test_state_whenHasErrorAndLargeMessage_returnMultipleErrorLinesStateSnapshot.1.png
  NatDSSnapShotTests/TextField/__Snapshots__/TextField+Snapshot+Tests/test_state_whenHasError_returnErrorStateSnapshot.1.png
  Sources/Public/Components/Field/TextField.swift
  Sources/Resources/Images.xcassets/Icons/IconOutlinedActionCancel.imageset/Contents.json
  Sources/Resources/Images.xcassets/Icons/IconOutlinedActionCancel.imageset/Icon _ Outlined _ Action _ Cancel.pdf
Labels: refactor

#204 [DSY-1736] feat: add badge configuration to shortcuts
  NatDS.xcodeproj/project.pbxproj
  NatDSSnapShotTests/Shortcut/NatShortcut+Snapshot+Tests.swift
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_default_with_badge_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_primary_with_badge_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_default_with_badge_hasValidSnapshot.1.png
  NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_primary_with_badge_hasValidSnapshot.1.png
  SampleApp/Sources/Sample/Components/Shortcut/ShortcutItemViewController.swift
  Sources/Public/Components/Shortcut/NatShortcut.swift
  Sources/Public/Components/Shortcut/ShortcutView.swift
  Tests/Core/ViewStyle/Shortcut/ShortcutContainedStyle+Spec.swift
  Tests/Core/ViewStyle/Shortcut/ShortcutOutlinedStyle+Spec.swift
  Tests/Public/Components/Shortcut/NatShortcut+Spec.swift
Labels: component: Shortcut

#215 chore: bumps version to 2.12.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore

#222 [DSY-963] Creates a Dot variant for Badge
  NatDS.xcodeproj/project.pbxproj
  NatDSSnapShotTests/Badge/Badgeable+Snapshot+Tests.swift
  NatDSSnapShotTests/Badge/NatBadge+Dot+Snapshot+Tests.swift
  NatDSSnapShotTests/Badge/NatBadge+Standard+Snapshot+Tests.swift
  NatDSSnapShotTests/Badge/__Snapshots__/Badgeable+Snapshot+Tests/test_badge_style_dot_alert_count_1_hasValidSnapshot.1.png
  NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Dot+Snapshot+Tests/test_badge_style_dot_alert_hasValidSnapshot.1.png
  NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Dot+Snapshot+Tests/test_badge_style_standard_alert_count_100_hasValidSnapshot.1.png
  NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Standard+Snapshot+Tests/test_badge_style_standard_alert_count_100_hasValidSnapshot.1.png
  NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Standard+Snapshot+Tests/test_badge_style_standard_alert_count_1_hasValidSnapshot.1.png
  NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Standard+Snapshot+Tests/test_badge_style_standard_alert_count_50_hasValidSnapshot.1.png
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/Badge/BadgeViewController.swift
  SampleApp/Sources/Sample/Components/Badge/BadgeableView.swift
  Sources/Public/Components/Badge/NatBadge+Color.swift
  Sources/Public/Components/Badge/NatBadge+Style.swift
  Sources/Public/Components/Badge/NatBadge.swift
  Tests/Public/Components/Badge/NatBadge+Dot+Spec.swift
  Tests/Public/Components/Badge/NatBadge+Standard+Spec.swift
  Tests/Public/Components/Badge/Protocol/Badgeable+Spec.swift
Labels: enhancement

#223 [DSY-1750] Chore: Bump version to 3.0.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
  SampleApp/Sources/Sample/Components/AppBar/AppBarDetailViewController.swift
  SampleApp/Sources/Sample/Components/Iconography/IconographyItemViewController.swift
  SampleApp/Sources/Sample/Components/NavigationDrawer/NavigationDrawerItemViewController.swift
Labels: breaking change, chore

#224 Docs: fix docs script + update docs
  docs/Getting started.md
  docs/How to use icons.md
  scripts/update_docs.sh
Labels: documentation

#226 [DSY-1727] Update/textfield password action icon
  NatDSSnapShotTests/TextField/TextField+Snapshot+Tests.swift
  NatDSSnapShotTests/TextField/__Snapshots__/TextField+Snapshot+Tests/test_password_whenVisibilityIconIsSet_expectedShowIconOutlinedActionVisibility.1.png
  NatDSSnapShotTests/TextField/__Snapshots__/TextField+Snapshot+Tests/test_password_whenVisibilityIconIsSet_expectedShowIconOutlinedActionVisibilityOff.1.png
  SampleApp/Sources/Sample/Components/Field/TextFieldItemViewController.swift
  Sources/Core/Helpers/AssetsPath.swift
  Sources/Public/Components/Field/TextField.swift
  Sources/Public/Components/IconButton/NatIconButton.swift
  Sources/Resources/Images.xcassets/Icons/IconOutlinedActionVisibility.imageset/Contents.json
  Sources/Resources/Images.xcassets/Icons/IconOutlinedActionVisibility.imageset/IconOutlinedActionVisibility.pdf
  Sources/Resources/Images.xcassets/Icons/IconOutlinedActionVisibilityOff.imageset/Contents.json
  Sources/Resources/Images.xcassets/Icons/IconOutlinedActionVisibilityOff.imageset/IconOutlinedActionVisibilityOff.pdf
  Tests/Public/Components/IconButton/NatIconButton+Spec.swift
Labels: enhancement

#227 [DSY-1488] Refactor NatTag
  NatDSSnapShotTests/NavigationDrawer/__Snapshots__/NavigationDrawerItemCell+Snapshot+Tests/test_setTagTextWithSubItems_withLargeTitle_hasSnapshotWithTag.1.png
  NatDSSnapShotTests/NavigationDrawer/__Snapshots__/NavigationDrawerItemCell+Snapshot+Tests/test_setTagText_withLargeTitle_hasSnapshotWithTag.1.png
  NatDSSnapShotTests/Tag/NatTag+Snapshot+Tests.swift
  NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_style_default_alert_hasValidSnapshot.1.png
  NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_style_left_alert_hasValidSnapshot.1.png
  NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_style_right_alert_hasValidSnapshot.1.png
  SampleApp/Sources/Sample/Components/Tag/TagViewController.swift
  Sources/Public/Components/Tag/NatTag+Style.swift
  Sources/Public/Components/Tag/NatTag.swift
Labels: enhancement

#228 [DSY-1727] refactor: 💡 Updates textfield to fit with password button
  Sources/Public/Components/Field/Field.swift
  Sources/Public/Components/Field/TextField.swift
  Sources/Public/Components/IconButton/NatIconButton.swift
Labels: chore

#229 chore: 🤖 bumps version to 3.1.0
  NatDS.podspec
  NatDS.xcodeproj/project.pbxproj
  SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
Labels: chore
